line-length = 120
target-version = "py38"
exclude = [
    "leap_hardware/scripts/*.py",
    "leap_hardware/src/leap_hardware/*.py",
    "leap_sim/leapsim/*.py",
    "leap_task_B/*.py",
]

[lint]
select = ["E4", "E7", "E9", "F", "PL", "UP", "PTH"]
ignore = ["PTH123"]
unfixable = ["F401"]
